### PR TITLE
add vim plugin

### PR DESCRIPTION
**Pull request by rfhlmn**
- detect files that end in .tl as parti-time files
- add syntax highlighting of parti-time files

### CODE REVIEW

**Comment by JohannesFKnauf** [comment]
What a cool opportunity to teach an old emacser some vim plugin dev! Thanks a lot for submitting, @rfhlmn .

I just started the review. Applying your plugin as described in the README works like a charm. Great that you thought about that detail!

I think I will try to address some points before merging:
* In fact, [the `tl` syntax grammar](https://github.com/JohannesFKnauf/parti-time/blob/master/src/main/resources/tl/timeline_grammar.ebnf) intentionally does not have a concept of `#` comments (it might be, that it used to have it at some former point in time, though, not sure).
* The plugin should highlight categories instead of notes (or rather in addition to notes).
* The military time match rule also matches the ` ` trailing space, which technically should not be part of the highlighted string.

**Comment by rfhlmn** [comment]
Sure thing!

Very fair, to all of your points, I've patched the syntax file to take it all into consideration.

**Comment by JohannesFKnauf** [comment]
@rfhlmn Your improved solution looks excellent to me! Much more beautiful than my dilettante attempt. I went through it with the help of the [vim syntax doc](https://vimdoc.sourceforge.net/htmldoc/syntax.html). I can't judge how idiomatic that is, but it's certainly reasonable and understandable.

Please allow me a bit of nitpicking:
* I'd prefer a consistent use of regex syntax, i.e. `"\v^\d{4} .+"` instead of `"^\v\d{4} .+"`
* I'd prefer a logical grouping of the no-time line rule, i.e. `"^\v {4} .+"` instead of `"^\v {5}.+"` (In `tl`, the 4 spaces are the logical equivalent of the omitted `hhmm` time, the extra space is a separator)

**Comment by rfhlmn** [comment]
It's my first time creating one of these as well, but it seemed the cleaner approach, so I went with it. :grin: 

And to the rest: Fair enough, here's another set of patches!

**Comment by JohannesFKnauf** [comment]
Great! Thanks a lot for your contribution!

**Pull request merged**
